hplaser:
  name: HPLaser
  mac: 74:29:AF:08:65:96
  icon:
  picture:
  track: false

t430_vm_wiso:
  name: T430-VM-Wiso
  mac: AC:6F:BB:62:D9:B8
  icon:
  picture:
  track: false

alexa:
  name: alexa
  mac: FC:A6:67:A4:AB:61
  icon:
  picture:
  track: false

fritz_repeater_dg:
  name: fritz-repeater-DG
  mac: 22:A6:2F:B8:56:94
  icon:
  picture:
  track: false

fritz_box:
  name: fritz.box
  mac: E0:28:6D:11:40:6B
  icon:
  picture:
  track: false

fritz_repeater:
  name: fritz.repeater
  mac: 22:A6:2F:D9:35:58
  icon:
  picture:
  track: false

homeassistant:
  name: homeassistant
  mac: DC:A6:32:2D:10:20
  icon:
  picture:
  track: false

iphone6vonclara:
  name: iPhone6vonClara
  mac: 9A:43:E0:4A:8B:1A
  icon: mdi:cellphone
  picture:
  track: false

jpad_air_2:
  name: jPad-Air-2
  mac: 52:E5:15:40:6F:EB
  icon: mdi:tablet
  picture:
  track: false

s2:
  name: s2
  mac: 50:02:91:ED:22:DF
  icon:
  picture:
  track: false

s3:
  name: s3
  mac: 10:52:1C:F9:97:BF
  icon:
  picture:
  track: false

s4:
  name: s4
  mac: E0:98:06:9D:90:B0
  icon:
  picture:
  track: false

s5:
  name: s5
  mac: 10:52:1C:F1:1D:6B
  icon:
  picture:
  track: false

s6:
  name: s6
  mac: 48:3F:DA:4D:06:33
  icon:
  picture:
  track: false

s7:
  name: s7
  mac: 10:52:1C:F1:22:3A
  icon:
  picture:
  track: false

swajpad:
  name: swajPad
  mac: B0:65:BD:EA:94:BF
  icon: mdi:tablet
  picture:
  track: false

t430_lan:
  name: t430-lan
  mac: 28:D2:44:22:A9:79
  icon:
  picture:
  track: false

0e_58_d5_5c_44_3a:
  name: 0e_58_d5_5c_44_3a
  mac: 0E:58:D5:5C:44:3A
  icon:
  picture:
  track: false

fa_60_89_c5_02_fc:
  name: fa_60_89_c5_02_fc
  mac: FA:60:89:C5:02:FC
  icon:
  picture:
  track: false

66_43_4d_45_c2_8c:
  name: jPhone
  mac: 66:43:4D:45:C2:8C
  icon: mdi:cellphone
  picture:
  track: false

# fritzbox tracker stuff
iPhone:
  hide_if_away: false
  name: iPhone
  mac: 48:26:2c:91:83:f0
  icon: mdi:cellphone
  picture: local/swa.jpg
  track: true

fritz_repeater_2:
  name: fritz.repeater
  mac: 0E:96:D7:A1:56:2D
  icon:
  picture:
  track: false

jphone:
  name: Jphone
  mac:
  icon:
  picture:
  track: false

iphone_von_anna:
  name: Vonanna
  mac:
  icon:
  picture:
  track: false

julia_x1:
  name: Julia-X1
  mac: 28:B2:BD:52:C7:FE
  icon:
  picture:
  track: false

pc_192_168_178_26:
  name: PC-192-168-178-26
  mac: A0:02:DC:84:A6:6E
  icon:
  picture:
  track: false

s7_2:
  name: s7
  mac: 48:3F:DA:4C:C1:B1
  icon:
  picture:
  track: false

rainers_ipad:
  name: Rainers-iPad
  mac: EA:EF:D9:99:21:0D
  icon:
  picture:
  track: false

volvo_su_xp1654:
  name: SU-XP1654
  mac:
  icon: mdi:car
  picture:
  track: false

bs2002swc:
  name: BS2002SWC
  mac: 28:7F:CF:81:A3:44
  icon:
  picture:
  track: false

anna_t430_swa:
  name: ANNA-T430--swa
  mac: A4:4E:31:A2:9B:E4
  icon:
  picture:
  track: false

android_d37a7c76a2aad137:
  name: android-d37a7c76a2aad137
  mac: 10:D3:8A:AA:24:C9
  icon:
  picture:
  track: false

annas_air:
  name: Annas-Air
  mac: 98:E0:D9:96:D4:0D
  icon:
  picture:
  track: false

swaiphone_2:
  name: swaiPhone_2
  mac: 48:4B:AA:AC:02:31
  icon:
  picture:
  track: false

christas_iphone:
  name: Christas-iPhone
  mac: 5C:F7:E6:D8:F3:58
  icon:
  picture:
  track: false

iphone7:
  name: iPhone7
  mac: 62:8E:3D:5E:1E:AA
  icon:
  picture:
  track: false

homeassistant_2:
  name: homeassistant
  mac: DC:A6:32:2D:10:1F
  icon:
  picture:
  track: false

toniebox:
  name: Toniebox
  mac: 50:33:8B:F7:6B:74
  icon:
  picture:
  track: false

s13:
  name: s13
  mac: 40:F5:20:26:1B:7B
  icon:
  picture:
  track: false

s9:
  name: s9
  mac: 8C:AA:B5:EE:E5:D9
  icon:
  picture:
  track: false

t430_wlan:
  name: t430-wlan
  mac: A4:4E:31:40:D9:8C
  icon:
  picture:
  track: false

s10:
  name: s10
  mac: 8C:AA:B5:EB:00:BE
  icon:
  picture:
  track: false

bs2002swc_itbwi_net:
  name: BS2002SWC.itbwi.net
  mac: 00:68:EB:8A:0B:9C
  icon:
  picture:
  track: false

iphone6vonclara_2:
  name: iPhone6vonClara
  mac: 1C:91:48:58:0E:19
  icon:
  picture:
  track: false

toniebox_2:
  name: Toniebox
  mac: 50:33:8B:F8:30:6D
  icon:
  picture:
  track: false

s11:
  name: s11
  mac: 8C:AA:B5:EA:6A:DC
  icon:
  picture:
  track: false

bs100at4c:
  name: BS100AT4C
  mac: 14:AB:C5:62:AF:9D
  icon:
  picture:
  track: false

ems_esp:
  name: ems-esp
  mac: E8:DB:84:D0:E7:E7
  icon:
  picture:
  track: false

ems_esp_2:
  name: ems-esp
  mac: 3C:61:05:03:B7:EC
  icon:
  picture:
  track: false

ipad_2:
  name: iPad-2
  mac: 12:00:10:20:A4:E9
  icon:
  picture:
  track: false

iphone_3:
  name: iPhone
  mac: 8E:66:A7:B8:52:F6
  icon:
  picture:
  track: false

ipad:
  name: iPad
  mac: 94:E9:6A:79:18:C0
  icon:
  picture:
  track: false

hp_bwi:
  name: hp-bwi
  mac: 3C:52:82:4B:68:CF
  icon:
  picture:
  track: false

bs2008rzc:
  name: BS2008RZC
  mac: F8:0D:AC:65:31:FE
  icon:
  picture:
  track: false

bs2008rzc_itbwi_net:
  name: BS2008RZC.itbwi.net
  mac: E0:D4:E8:41:81:88
  icon:
  picture:
  track: false

gas3:
  name: gas3
  mac: 9C:9C:1F:E3:D5:DC
  icon:
  picture:
  track: false
