- id: '1608063965030'
  alias: Wenn neue Version dann Nachricht an Stefan
  trigger:
  - platform: state
    entity_id: binary_sensor.updater
    from: 'off'
    to: 'on'
  action:
  - service: notify.mobile_app_swaiphone
    data:
      title: Hinweis
      message: Home Assistant  {{ state_attr('binary_sensor.updater', 'newest_version')
        }}  is now available.
  mode: single
- id: '1608480614730'
  alias: Wenn Haustür geöffnet wird und dunkel draußen, dann Flur-EG Licht an und
    LED-Fluter an
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.haustur
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.dunkel_draussen
    state: 'on'
  action:
  - type: turn_on
    device_id: d824de0a6c667da98e0f508d5d4129e5
    entity_id: switch.eg_flur_licht
    domain: switch
  - type: turn_on
    device_id: 33202a9524f56b2023ed57884e81af71
    entity_id: switch.shelly25_garage_channel_2
    domain: switch
  mode: single
- id: '1608567664971'
  alias: zDummy to logfile
  description: ''
  trigger:
  - platform: state
    entity_id: automation.dummy
    attribute: last_triggered
  condition: []
  action:
  - service: system_log.write
    data:
      message: Dummy to logfile
      level: warning
      logger: swa-automation
  mode: single
- id: '1608633463304'
  alias: Schlafzimmer Rolladen runter etwas nach Sonnenuntergang
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 00:30:00
  condition: []
  action:
  - service: cover.set_cover_position
    data:
      position: 15
    entity_id: cover.eltern_schlafzimmer
  mode: single
- id: '1608636183988'
  alias: Wenn Fenster zu lange offen und kalt, dann Nachricht an alle
  description: ''
  trigger:
  - platform: state
    from: 'off'
    for: 00:10:00
    to: 'on'
    entity_id: group.dachfenster
  - platform: state
    entity_id: group.ogfenster
    from: 'off'
    for: 00:10:00
    to: 'on'
  - platform: state
    entity_id: group.egfenster
    from: 'off'
    to: 'on'
    for: 00:10:00
  condition:
  - condition: numeric_state
    entity_id: weather.homeassistant
    value_template: '{{ state.attributes.temperature }}'
    below: '15'
  action:
  - service: notify.all_ios_parent_phones
    data:
      title: Hinweis
      message: '{% set w = expand( trigger.entity_id ) | selectattr(''state'', ''eq'',
        ''on'') | map(attribute=''name'') | list %} Fenster {{ w }} aus Gruppe {{
        trigger.to_state.attributes.friendly_name }} ist zu lange ({{trigger.for}}
        min) offen.'
  mode: single
- id: l1k3
  alias: push HA configuration to GitHub repo
  trigger:
  - at: '23:23:00'
    platform: time
  action:
  - data:
      addon: a0d7b954_ssh
      input: /config/gitpush.sh
    service: hassio.addon_stdin
- id: '1609014775930'
  alias: Notify when someone enters or leaves a zone
  description: Notify when someone enters or leaves a zone
  trigger:
  - platform: state
    entity_id: person.stefan
  - platform: state
    entity_id: person.anna
  - platform: state
    entity_id: person.julia
  condition:
  - condition: template
    value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'
  action:
  - service: notify.mobile_app_swaiphone
    data:
      title: Location update (old) {{ states.sensor.time.state }}
      message: '{{ trigger.to_state.attributes.friendly_name }} {% if trigger.to_state.state
        == ''not_home'' %}has left {{ trigger.from_state.state }}{% endif %}{% if
        trigger.from_state.state == ''not_home'' %}arrived at {{ trigger.to_state.state
        }}{% endif %}'
  mode: single
- id: '1609245232653'
  alias: zAußenlicht an, wenn dunkel draußen
  description: Außenlicht an, wenn dunkel draußen
  trigger:
  - platform: state
    entity_id: binary_sensor.dunkel_draussen
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.shellyswitch25_483fda4cc1b1_channel_1
  mode: single
- id: '1609245648666'
  alias: zAußenlicht aus, wenn hell draußen
  description: Außenlicht aus, wenn hell draußen
  trigger:
  - platform: state
    entity_id: binary_sensor.dunkel_draussen
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.shellyswitch25_483fda4cc1b1_channel_1
  mode: single
- id: cam1
  alias: zMotioneye - Camera1 - Motion started
  trigger:
  - platform: webhook
    webhook_id: motioneye-camera1-started
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.camera1_motion_detected
  mode: single
- id: cam2
  alias: zMotioneye - Camera1 - Motion ended
  trigger:
  - platform: webhook
    webhook_id: motioneye-camera1-ended
  action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.camera1_motion_detected
  mode: single
- id: cam3
  alias: zEnable motion detection
  trigger:
  - platform: state
    entity_id: input_boolean.camera_motion_detection
    to: 'on'
  action:
  - service: rest_command.camera_motion_start
  mode: single
- id: cam4
  alias: zDisable motion detection
  trigger:
  - platform: state
    entity_id: input_boolean.camera_motion_detection
    to: 'off'
  action:
  - service: rest_command.camera_motion_pause
  mode: single
- id: '1609858165994'
  alias: Windfanglicht an, wenn dunkel draußen
  description: Windfanglicht an, wenn dunkel draußen
  trigger:
  - platform: state
    entity_id: binary_sensor.dunkel_draussen
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.shellyswitch25_483fda4cc1b1_channel_2
  mode: single
- id: '1609858227328'
  alias: Windfanglicht  aus, wenn hell draußen
  description: Windfanglicht  aus, wenn hell draußen
  trigger:
  - platform: state
    entity_id: binary_sensor.dunkel_draussen
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.shellyswitch25_483fda4cc1b1_channel_2
  mode: single
- id: '1609924669215'
  alias: zSchließe Volvo ab, wenn zuhause und offen
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.volvo_zuhause_und_offen
    from: 'false'
    to: 'True'
  condition: []
  action:
  - service: lock.lock
    data:
      entity_id: lock.su_xp1654_door_lock
  mode: single
- id: julia_arrives_home
  alias: yJulia Arrives Home
  trigger:
  - platform: state
    entity_id: sensor.jphone_zone_name
    to: Home
  condition:
  - condition: template
    value_template: '{{states("sensor.swaiphone_zone_distance") | float <= 0.2}}'
  action:
  - service: script.notify_swaiphone
    data:
      title: julia Arrives Home
      message: 'Zone: {{ trigger.from_state.state }} --> {{ trigger.to_state.state
        }}, Distance: {{ states.sensor.jphone_zone_distance.state }}'
  mode: single
- alias: yJulia Leaves Home
  id: julia_leaves_home
  trigger:
  - platform: state
    entity_id: sensor.jphone_zone_name
    to: Away
  condition:
  - condition: template
    value_template: '{{trigger.from_state.state == "Home"}}'
  - condition: template
    value_template: '{{states("sensor.jphone_zone_distance") | float > 0}}'
  action:
  - service: script.notify_swaiphone
    data:
      title: julia Leaves Home
      message: 'Zone: {{ trigger.from_state.state }} --> {{ trigger.to_state.state
        }}, Distance: {{ states("sensor.jphone_zone_distance") }}'
- alias: yJulia Leaves Zone
  id: julia_leaves_zone
  trigger:
  - platform: state
    entity_id: sensor.jphone_zone_name
    to: Away
  condition:
  - condition: template
    value_template: '{{trigger.from_state.state != "Home"}}'
  - condition: template
    value_template: '{{states("sensor.jphone_zone_distance") | float > 0}}'
  action:
  - service: script.notify_swaiphone
    data:
      title: julia Leaves Zone
      message: 'Zone: {{ trigger.from_state.state }} --> {{ trigger.to_state.state
        }}, Distance: {{ states.sensor.jphone_zone_distance.state }}'
- id: stefan_arrives_home
  alias: yStefan Arrives Home
  trigger:
  - platform: state
    entity_id: sensor.swaiphone_zone_name
    to: Home
  condition:
  - condition: template
    value_template: '{{states("sensor.swaiphone_zone_distance") | float <= 0.2}}'
  action:
  - service: script.notify_swaiphone
    data:
      title: stefan Arrives Home
      message: 'Zone: {{ trigger.from_state.state }} --> {{ trigger.to_state.state
        }}, Distance: {{ states.sensor.swaiphone_zone_distance.state }}'
  mode: single
- id: stefan_leaves_home
  alias: yStefan Leaves Home
  trigger:
  - platform: state
    entity_id: sensor.swaiphone_zone_name
    to: Away
  condition:
  - condition: template
    value_template: '{{states("sensor.swaiphone_zone_distance") | float > 0}}'
  action:
  - service: script.notify_swaiphone
    data:
      title: stefan Leaves Home
      message: 'Zone: {{ trigger.from_state.state }} --> {{ trigger.to_state.state
        }}, Distance: {{ states("sensor.swaiphone_zone_distance") }}'
  mode: single
- alias: yStefan Leaves Zone
  id: stefan_leaves_zone
  trigger:
  - platform: state
    entity_id: sensor.swaiphone_zone_name
    to: Away
  condition:
  - condition: template
    value_template: '{{trigger.from_state.state != "Home"}}'
  - condition: template
    value_template: '{{states("sensor.swaiphone_zone_distance") | float > 0}}'
  action:
  - service: script.notify_swaiphone
    data:
      title: stefan Leaves Zone
      message: 'Zone: {{ trigger.from_state.state }} --> {{ trigger.to_state.state
        }}, Distance: {{ states.sensor.swaiphone_zone_distance.state }}'
- id: '1611480761802'
  alias: Wenn Garage geöffnet wird und dunkel draußen, dann Flur-EG Licht an und LED-Fluter
    an
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.garagentur
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.dunkel_draussen
    state: 'on'
  action:
  - type: turn_on
    device_id: d824de0a6c667da98e0f508d5d4129e5
    entity_id: switch.eg_flur_licht
    domain: switch
  - type: turn_on
    device_id: 33202a9524f56b2023ed57884e81af71
    entity_id: switch.shelly25_garage_channel_2
    domain: switch
  mode: single
- id: '1611495931370'
  alias: Kellerpumpe Treppe läuft an
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.shellys_keller_pumpe_treppe_power
    above: 5
    for: 00:00:03
  condition: []
  action:
  - service: counter.increment
    data: {}
    entity_id: counter.kellerpumpe
  mode: single
- id: '1611496375383'
  alias: Kellerpumpe Zähler zurücksetzen
  description: ''
  trigger:
  - platform: time
    at: 00:00
  condition: []
  action:
  - service: counter.reset
    data: {}
    entity_id: counter.kellerpumpe
  mode: single
- id: '1611502164716'
  alias: zFake
  description: ''
  trigger:
  - platform: time
    at: 00:00
  condition: []
  action:
  - service: script.notify_swaiphone
    data:
      title: Hinweis
      message: Fake automation
  mode: single
- id: anna_arrives_home
  alias: yAnna Arrives Home
  trigger:
  - platform: state
    entity_id: sensor.swaiphone_zone_name
    to: Home
  - platform: template
    value_template: '{{states("sensor.iphone_von_anna_zone_distance") | float <= 0.2}}'
  action:
  - service: script.notify_swaiphone
    data:
      title: Anna Arrives Home
      message: 'Zone: {{ trigger.from_state.state }} --> {{ trigger.to_state.state
        }}, Distance: {{ states.sensor.iphone_von_anna_zone_distance.state }}'
  mode: single
- alias: yAnna Leaves Home
  id: anna_leaves_home
  trigger:
  - platform: state
    entity_id: sensor.iphone_von_anna_zone_name
    to: Away
  condition:
  - condition: template
    value_template: '{{trigger.from_state.state == "Home"}}'
  - condition: template
    value_template: '{{states("sensor.iphone_von_anna_zone_distance") | float > 0}}'
  action:
  - service: script.notify_swaiphone
    data:
      title: Anna Leaves Home
      message: 'Zone: {{ trigger.from_state.state }} --> {{ trigger.to_state.state
        }}, Distance: {{ states("sensor.iphone_von_anna_zone_distance") }}'
- alias: yAnna Leaves Zone
  id: anna_leaves_zone
  trigger:
  - platform: state
    entity_id: sensor.iphone_von_anna_zone_name
    to: Away
  condition:
  - condition: template
    value_template: '{{trigger.from_state.state != "Home"}}'
  - condition: template
    value_template: '{{states("sensor.iphone_von_anna_zone_distance") | float > 0}}'
  action:
  - service: script.notify_swaiphone
    data:
      title: Anna Leaves Zone
      message: 'Zone: {{ trigger.from_state.state }} --> {{ trigger.to_state.state
        }}, Distance: {{ states.sensor.iphone_von_anna_zone_distance.state }}'
- id: '1611515523821'
  alias: Alexa Media Player TTS/Announce from Lovelace UI
  description: ''
  use_blueprint:
    path: NachtaktiverHalbaffe/alexa-tts-announcement-from-lovelace-ui-and-without-nabu-casa-alexa-media-player.yaml
    input:
      message: input_text.swa_alexa_text
      target: input_select.swa_alexa_device
- id: swa1
  alias: Notify about Fritzphone state
  trigger:
  - platform: state
    entity_id: sensor.fritzphone
  action:
  - service: notify.all_ios_parent_phones
    data:
      title: FritzPhone
      message: "{% if is_state(\"sensor.fritzphone\", \"idle\") %}\n  Phone is idle\n\
        {% elif is_state(\"sensor.fritzphone\", \"dialing\") %}\n  Calling {{ state_attr('sensor.fritzphone',\
        \ 'to_name') }} ({{ state_attr('sensor.fritzphone', 'to') }})\n{% elif is_state(\"\
        sensor.fritzphone\", \"ringing\") %}\n  Incoming call from {{ state_attr('sensor.fritzphone',\
        \ 'from_name') }} ({{ state_attr('sensor.fritzphone', 'from') }})\n{% else\
        \ %}\n  Talking to {{ state_attr('sensor.fritzphone', 'with_name') }} ({{\
        \ state_attr('sensor.fritzphone', 'with') }})\n{% endif %}"
  mode: single
- id: '1612096410696'
  alias: Waschmaschine fertig (v2)
  description: Waschmaschine fertig
  use_blueprint:
    path: Sbyx/notify-or-do-something-when-an-appliance-like-a-dishwasher-or-washing-machine-finishes.yaml
    input:
      finishing_hysteresis: '5'
      power_sensor: sensor.shellys_wama_power
      starting_threshold: 100
      starting_hysteresis: '3'
      finishing_threshold: 40
      actions:
      - service: notify.all_ios_parent_phones
        data:
          title: Hinweis
          message: Waschmaschine ist fertig seit {{ now().hour }}:{{ now().minute
            }}. (v2)
      - service: script.turn_on
        data: {}
        entity_id: script.swa
- id: '1612163701541'
  alias: 'yJulia Arrives Zone '
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.jphone_zone_name
    from: Away
  condition:
  - condition: template
    value_template: '{{trigger.from_state.state != "Home"}}'
  - condition: template
    value_template: '{{states("sensor.jphone_zone_distance") | float > 0}}'
  - condition: template
    value_template: '{{trigger.to_state.state != "stationary"}}'
  - condition: template
    value_template: '{{trigger.to_state.state != "Home"}}'
  action:
  - service: script.notify_swaiphone
    data:
      title: julia Arrives at Zone
      message: 'Zone: {{ trigger.from_state.state }} --> {{ trigger.to_state.state
        }}, Distance: {{ states.sensor.jphone_zone_distance.state }}'
  mode: single
