- id: '1608063965030'
  alias: Wenn neue Version dann Nachricht an Stefan
  trigger:
  - platform: state
    entity_id: binary_sensor.updater
    from: 'off'
    to: 'on'
  action:
  - service: notify.mobile_app_swaiphone
    data:
      title: New Home Assistant Release
      message: Home Assistant  {{ state_attr('binary_sensor.updater', 'newest_version')
        }}  is now available.
  mode: single
- id: '1608480614730'
  alias: Wenn Haustür geöffnet wird und dunkel draußen, dann Flur-EG Licht an und
    LED-Fluter an
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.haustur
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.dunkel_draussen
    state: 'on'
  action:
  - type: turn_on
    device_id: d824de0a6c667da98e0f508d5d4129e5
    entity_id: switch.eg_flur_licht
    domain: switch
  - type: turn_on
    device_id: 33202a9524f56b2023ed57884e81af71
    entity_id: switch.shelly25_garage_channel_2
    domain: switch
  mode: single
- id: '1608494074501'
  alias: Dummy
  description: ''
  trigger:
  - platform: state
    entity_id: automation.new_automation
  condition: []
  action:
  - service: notify.mobile_app_swaiphone
    data:
      title: Dummy
      message: foobar
  mode: single
- id: '1608549888374'
  alias: Wenn ein Dachfenster offen ist und Regen zu erwarten ist, dann Nachricht
    an alle.
  description: ''
  trigger:
  - platform: state
    from: 'off'
    to: 'on'
    entity_id: group.dachfenster
  condition:
  - condition: state
    entity_id: sensor.rainy_day
    state: 'false'
  action:
  - service: notify.all_ios_parent_phones
    data:
      title: Dachfenster
      message: Dachfenster offen und Vorhersage sagt {{ state_attr('weather.homeassistant',
        'forecast')[0].precipitation }}mm Regen.
  - service: system_log.write
    data:
      message: Dachfenster bei Regenvorhersage geoeffnet.
      level: warning
      logger: swa-automations
  mode: single
- id: '1608567664971'
  alias: Dummy to logfile
  description: ''
  trigger:
  - platform: state
    entity_id: automation.dummy
    attribute: last_triggered
  condition: []
  action:
  - service: system_log.write
    data:
      message: Dummy to logfile
      level: warning
      logger: swa-automation
  mode: single
- id: '1608633463304'
  alias: Schlafzimmer Rolladen runter nach Sonnenuntergang
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 00:30:00
  condition: []
  action:
  - service: cover.set_cover_position
    data:
      position: 15
    entity_id: cover.eltern_schlafzimmer
  - service: system_log.write
    data:
      message: Schlafzimmer Rolladen runter nach Sonnenuntergang
      level: warning
      logger: swa-automations
  mode: single
- id: '1608636183988'
  alias: Wenn Fenster zu lange offen, dann Nachricht an alle
  description: ''
  trigger:
  - platform: state
    from: 'off'
    for: 0:10:00
    to: 'on'
    entity_id: group.fenster
  condition: []
  action:
  - service: notify.all_ios_parent_phones
    data:
      title: Fenster
      message: Steht zu lange offen. Es hat {{ state_attr('weather.homeassistant',
        'temperature') }} Grad draußen.
  - service: system_log.write
    data:
      message: Wenn Fenster zu lange offen, dann Nachricht an alle
      level: warning
      logger: swa-automations
  mode: single
- id: l1k3
  alias: push HA configuration to GitHub repo
  trigger:
  - at: '23:23:00'
    platform: time
  action:
  - data:
      addon: a0d7b954_ssh
      input: /config/gitpush.sh
    service: hassio.addon_stdin
- id: '1609014775930'
  alias: Notify when someone enters or leaves a zone
  description: Notify when someone enters or leaves a zone
  trigger:
  - platform: state
    entity_id: person.stefan
  - platform: state
    entity_id: person.anna
  - platform: state
    entity_id: person.julia
  condition:
  - condition: template
    value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'
  action:
  - service: notify.mobile_app_swaiphone
    data:
      title: Location update {{ states.sensor.time.state }}
      message: '{{ trigger.to_state.attributes.friendly_name }} {% if trigger.to_state.state
        == ''not_home'' %} has left {{ trigger.from_state.state }}{% endif %}{% if
        trigger.from_state.state == ''not_home'' %}arrived at {{ trigger.to_state.state
        }}{% endif %}'
  mode: single
- id: '1609245232653'
  alias: Außenlicht an, wenn dunkel draußen
  description: Außenlicht an, wenn dunkel draußen
  trigger:
  - platform: state
    entity_id: binary_sensor.dunkel_draussen
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.shellyswitch25_483fda4cc1b1_channel_1
  mode: single
- id: '1609245648666'
  alias: Außenlicht aus, wenn hell draußen
  description: Außenlicht aus, wenn hell draußen
  trigger:
  - platform: state
    entity_id: binary_sensor.dunkel_draussen
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.shellyswitch25_483fda4cc1b1_channel_1
  mode: single
- id: cam1
  alias: Motioneye - Camera1 - Motion started
  trigger:
  - platform: webhook
    webhook_id: motioneye-camera1-started
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.camera1_motion_detected
  mode: single
- id: cam2
  alias: Motioneye - Camera1 - Motion ended
  trigger:
    platform: webhook
    webhook_id: motioneye-camera1-ended
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.camera1_motion_detected
- id: cam3
  alias: Enable motion detection
  trigger:
  - platform: state
    entity_id: input_boolean.camera_motion_detection
    to: 'on'
  action:
    service: rest_command.camera_motion_start
- id: cam4
  alias: Disable motion detection
  trigger:
  - platform: state
    entity_id: input_boolean.camera_motion_detection
    to: 'off'
  action:
    service: rest_command.camera_motion_pause
- id: '1609858165994'
  alias: Windfanglicht an, wenn dunkel draußen
  description: Windfanglicht an, wenn dunkel draußen
  trigger:
  - platform: state
    entity_id: binary_sensor.dunkel_draussen
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.shellyswitch25_483fda4cc1b1_channel_2
  mode: single
- id: '1609858227328'
  alias: Windfanglicht  aus, wenn hell draußen
  description: Windfanglicht  aus, wenn hell draußen
  trigger:
  - platform: state
    entity_id: binary_sensor.dunkel_draussen
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.shellyswitch25_483fda4cc1b1_channel_2
  mode: single
- id: '1609924669215'
  alias: Schließe Volvo ab, wenn zuhause und offen
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.volvo_zuhause_und_offen
    from: 'false'
    to: 'True'
  condition: []
  action:
  - service: lock.lock
    data:
      entity_id: lock.su_xp1654_door_lock
  mode: single
- id: '1610727869121'
  alias: Pumpe im Keller angelaufen
  description: ''
  use_blueprint:
    path: Sbyx/notify-or-do-something-when-an-appliance-like-a-dishwasher-or-washing-machine-finishes.yaml
    input:
      power_sensor: sensor.shellys_keller_pumpe_treppe_power
      starting_hysteresis: '0.25'
      actions:
      - service: notify.all_ios_parent_phones
        data:
          title: Info
          message: Pumpe im Keller ist angegangen.
      finishing_hysteresis: '0.25'
      finishing_threshold: '5'
- id: swa_leaves_zone
  alias: Stefan Leaves Zone
  trigger:
  - platform: state
    entity_id: sensor.swaiphone_last_zone_name1
    to: Away
  condition:
  - condition: template
    value_template: '{{trigger.from_state.state != "Home"}}'
  - condition: template
    value_template: '{{states("sensor.swaiphone_zone_distance") | float > 0}}'
  - condition: state
    entity_id: input_boolean.ha_started_flag
    state: 'on'
  action:
  - service: notify.all_ios_parent_phones
    data:
      title: Stefan Leaves Zone
      message: Zone {{ trigger.from_state.state }} --> {{ trigger.to_state.state }},
        Distance {{ states.sensor.swaiphone_zone_distance.state }}
  mode: single
- id: swa_arrives_home
  alias: Stefan Arrives Home
  trigger:
  - platform: state
    entity_id: sensor.swaiphone_zone_name1
    to: Home
  - platform: template
    value_template: '{{states("sensor.swaiphone_zone_distance") | float <= 0.2}}'
  condition:
  - condition: state
    entity_id: input_boolean.gary_driving_flag
    state: 'on'
  action:
  - service: notify.all_ios_parent_phones
    data:
      title: Stefan Arrives Home
      message: Zone {{ trigger.from_state.state }} --> {{ trigger.to_state.state }},
        Distance {{ states.sensor.swaiphone_zone_distance.state }}
  mode: single
- id: swa_leaves_home
  alias: Stefan Leaves Home
  trigger:
  - platform: state
    entity_id: sensor.swaiphone_zone_name1
    to: Away
  condition:
  - condition: template
    value_template: '{{trigger.from_state.state == "Home"}}'
  - condition: template
    value_template: '{{states("sensor.swaiphone_zone_distance") | float > 0}}'
  - condition: state
    entity_id: input_boolean.ha_started_flag
    state: 'on'
  action:
  - service: notify.all_ios_parent_phones
    data:
      title: Stefan Leaves Home
      message: 'Zone: {{ trigger.from_state.state }} --> {{ trigger.to_state.state
        }}, Distance: {{ states.sensor.swaiphone_zone_distance }}'
