#
#
#
- platform: template
  sensors:

    camera1_motion:
      friendly_name: "iPhone Camera - Movement"
      device_class: motion
      value_template: "{{ is_state('input_boolean.camera1_motion_detected', 'on') }}"
      
    garagentur:
      friendly_name: "Garagentür"
      device_class: garage_door
      # off = closed; on = open
      value_template: "{{ is_state('cover.garage_door', 'open') }}"
      
    dunkel_draussen:
      friendly_name: "Dunkel draußen"
      value_template: >-
        {% if now().hour > 12 %}
        {{ state_attr('sun.sun', 'elevation')|float < 3 }}
        {% else %}
        {{ state_attr('sun.sun', 'elevation')|float < -3 }}
        {% endif %}
        
    nachts_tuerauf:
      friendly_name: "Nachts und Tuer geht auf"
      value_template: >-
        {% set p0 = states('group.tueren') == "on" %}
        {% set p1 = now().hour > 21 or now().hour < 6 %}
        {{ 'true' if p0 and p1 else 'false' }}
      attribute_templates:
        offenetuer: "{% set w = expand( 'group.tueren' ) | selectattr('state', 'eq', 'on') | map(attribute='name') | list %}{{ w }}"
