
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml
  customize_glob:
    "binary_sensor.fenster*":
      device_class: window
#
# check out https://www.home-assistant.io/lovelace/dashboards-and-views/
#
# lovelace:
  # mode: yaml
  # resources:
    # - url: /local/lovelace-auto-entities/auto-entities.js
      # type: module
#
#
#
frontend:
  themes: !include_dir_merge_named themes

#
# uncomment to increase loglevel
#
# logger:
  # default: info
  # logs:
    # custom_components.icloud3.pyicloud_ic3: debug
    # custom_components.icloud3.device_tracker: debug

# logger:
  # default: warn
  # logs:
    # homeassistant.components.recorder: debug
# # temporary solution as per https://github.com/emsesp/EMS-ESP/issues/756
    # homeassistant.helpers.template: error
# # lets see more stuff in the logs from mqtt
    # homeassistant.components.mqtt: debug

#
# avoid template errors in ems-esp
#
logger:
  default: warning
  logs:
    homeassistant.helpers.template: error
#  see https://github.com/home-assistant/core/issues/58653 for next line
    fritzconnection: info
# for reolink
#    custom_components.reolink_dev: debug
#    custom_components.reolink_dev.base.data: warning
#    reolink: debug

#
# to turn on my pc
#
wake_on_lan:
#
# Text to speech
#
tts:
  - platform: google_translate
    language: 'de'
    service_name: google_translate_say
    base_url: !secret base_url
#
#
#
zone: !include zones.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
notify: !include notifications.yaml
sensor: !include sensors.yaml
device_tracker: !include devicetrackers.yaml
#alert: !include alerts.yaml
http: !include http.yaml
cover: !include covers.yaml
volvooncall: !include volvo.yaml
switch: !include switches.yaml
homekit: !include homekit.yaml
template: !include_dir_merge_list templates/

#
# for camera stuff to work
# see https://community.home-assistant.io/t/motioneye-integration/194350
#
stream:
camera: !include cameras.yaml
#
#
#
input_boolean: !include input_booleans.yaml
binary_sensor: !include binary_sensors.yaml
rest_command: !include rest_commands.yaml

#
#
recorder:
  db_url: !secret db_url
  purge_keep_days: 7
  exclude:
    entity_globs:
      - sensor.adguard*
      - binary_sensor.*overheating
      - binary_sensor.*overpowering
      - device_tracker.*
      - sensor.iphone*
      - sensor.jphone*
      - sensor.stefans_ipad*
      - sensor.swaiphone*
      - sensor.thermostat_date*
      - sensor.fritz*
      - sensor.system*
      - switch.adguard*
    entities:
      - sensor.icloud3_event_log
      - sensor.swaiphone_info
      - sensor.jphone_info
      - sensor.iphone_von_anna_info
      - sensor.smlreaderdeviceid
      - sensor.smlreadermanufacturer
#
#
#
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb
  max_retries: 3
  default_measurement: state
  include:
    entities:
      - weather.home
      - weather.openweathermap
      - weather.accuweather
      - binary_sensor.heating_active
      - binary_sensor.warm_water_dhw_active      
      - sensor.swaweathermetno
      - sensor.swaweathermetno_condition
      - sensor.swaweathermetno_templow
      - sensor.swaweathermetno_temphigh
      - counter.kellerpumpe
      - counter.dew_fans
      - climate.roofac
#      - sensor.roofac_uptime
#      - sensor.gas3_uptime
      - climate.sleepac
#      - sensor.sleepac_uptime
      - sensor.regen_heute
      - sensor.rel_humidity
      - sensor.hum_abs_basement
      - sensor.smlreadertotalenergyconsumption
# floods the database as it comes in too often
#      - sensor.smlreaderpower
      - sensor.influxdb_db_size
      - sensor.gasverbrauch
    entity_globs:
      - sensor.shellys_keller*
      - sensor.boiler*
      - sensor.mixer*
      - sensor.thermostat*
      - sensor.solar*
      - sensor.accuweather*
      - sensor.openweathermap*
      - sensor.multi*
      - sensor.dew*
      - sensor.heating*
      - binary_sensor.boiler*
      - binary_sensor.mixer*
      - binary_sensor.solar*

#
#
counter:
    kellerpumpe:
      initial: 0
      step: 1
      icon: mdi:water-pump
    dew_fans:
      initial: 0
      step: 1
      icon: mdi:fan
#
# power and gas meters
#
utility_meter:
  gasverbrauch_hourly:
    source: sensor.gasverbrauch
    cycle: hourly
  gasverbrauch_daily:
    source: sensor.gasverbrauch
    cycle: daily
  gasverbrauch_weekly:  
    source: sensor.gasverbrauch
    cycle: weekly
  gasverbrauch_monthly:
    source: sensor.gasverbrauch
    cycle: monthly
  gasverbrauch_yearly:
    source: sensor.gasverbrauch
    cycle: yearly
#
#
  smlpower_hourly:
    source: sensor.smlreadertotalenergyconsumption
    cycle: hourly
  smlpower_daily:
    source: sensor.smlreadertotalenergyconsumption
    cycle: daily
  smlpower_weekly:
    source: sensor.smlreadertotalenergyconsumption
    cycle: weekly
  smlpower_monthly:
    source: sensor.smlreadertotalenergyconsumption
    cycle: monthly
  smlpower_yearly:
    source: sensor.smlreadertotalenergyconsumption
    cycle: yearly
    
#
#
  regen_daily:
    source: sensor.regen_heute
    cycle: daily
#
#
#
spotify:
  client_id: !secret spotify_clientid
  client_secret: !secret spotify_secret

#
#
#
panel_custom:
  - name: Server Controls
    url_path: config/server_control  # url_path needs to be unique for each panel_custom config
    sidebar_title: Server Controls
    sidebar_icon: mdi:server # https://materialdesignicons.com/
    module_url: /local/panel-redirect.js  # 'local' is '/config/www/'
  - name: Zones
    url_path: config/logs
    sidebar_title: Logs
    sidebar_icon: mdi:math-log
    module_url: /local/panel-redirect.js
