# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  # https://community.home-assistant.io/t/2024-5-tracking-down-instability-issues-caused-by-integrations/724441
  debug: true
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /config/temp
  customize_glob:
    "binary_sensor.fenster*":
      device_class: window
  #
  #
  #
  packages: !include_dir_named packages

#
# check out https://www.home-assistant.io/lovelace/dashboards-and-views/
#
# lovelace:
# mode: yaml
# resources:
# - url: /local/lovelace-auto-entities/auto-entities.js
# type: module
#
#
#
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /config/www/community/lovelace-card-mod/card-mod.js
#
# uncomment to increase loglevel
#
# logger:
# default: info
# logs:
# custom_components.icloud3.pyicloud_ic3: debug
# custom_components.icloud3.device_trackbug

# logger:
# default: warn
# logs:
# homeassistant.components.recorder: debug
# # temporary solution as per https://github.com/emsesp/EMS-ESP/issues/756
# homeassistant.helpers.template: error
# # lets see more stuff in the logs from mqtt
# homeassistant.components.mqtt: debug

logger:
  default: info
  logs:
    #
    # avoid template errors in ems-esp
    #
    homeassistant.helpers.template: error
    custom_components.evcc_intg: debug
    homeassistant.components.shell_command: notset
    # see https://github.com/home-assistant/core/issues/58653 for next line
    # homeassistant.components.fritz: debug
    # fritzconnection: info
    # for reolink
    # custom_components.reolink_dev: debug
    # custom_components.reolink_dev.base.data: warning
    # reolink: debug

#
# to turn on my pc
#
wake_on_lan:
#
# Text to speech
#
tts:
  - platform: google_translate
    language: "de"
    service_name: google_translate_say
# deprecated 2022.5
#    base_url: !secret base_url
#
#
#
zone: !include zones.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
notify: !include notifications.yaml
sensor: !include sensors.yaml
#device_tracker: !include devicetrackers.yaml
#alert: !include alerts.yaml
http: !include http.yaml
cover: !include covers.yaml
# deprecated yaml with 2022.9
#volvooncall: !include volvo.yaml
switch: !include switches.yaml
homekit: !include homekit.yaml
template: !include_dir_merge_list templates/
ios: !include ios.yaml

#
# power meter
#
# reload in HA with "manually created mqtt entities", see also customize.yaml
#
mqtt:
  sensor:
    - name: "SMLReaderManufacturer"
      state_topic: "homeassistant/sensor/smartmeter/sensor/1/obis/1-0:96.50.1/1/value"
    - name: "SMLReaderDeviceID"
      state_topic: "homeassistant/sensor/smartmeter/sensor/1/obis/1-0:96.1.0/255/value"
    - name: "SMLReaderCounter"
      state_topic: "homeassistant/sensor/smartmeter/sensor/1/obis/1-0:1.8.0/255/value"
      unit_of_measurement: "kWh"
      device_class: energy
    - name: "SMLReaderPower"
      state_topic: "homeassistant/sensor/smartmeter/sensor/1/obis/1-0:16.7.0/255/value"
      unit_of_measurement: "W"
      device_class: power
    #
    #
    #
    - name: "DWD Last Rainfall"
      state_topic: "home-assistant/variable/last_rainfall"
      value_template: "{{ value }}"
      qos: 0
    - name: "DWD Last Rainfall Amount"
      state_topic: "home-assistant/variable/last_rainfall_amount"
      value_template: "{{ value }}"
      qos: 0

      #
      # Sensor data provided by EVCC add-on
      #
      # Negativ? einspeisen, Positiv? Netzbezug.
    - name: "EVCC Grid Power"
      unique_id: evcc_grid_power
      state_topic: "evcc/site/gridPower"
      unit_of_measurement: "W"
      device_class: power
      availability_topic: "evcc/status"
      qos: 0
      # verbrauch des Hauses ex Ladepunkte
    - name: "EVCC Homepower"
      unique_id: evcc_homepower
      state_topic: "evcc/site/homePower"
      unit_of_measurement: "W"
      availability_topic: "evcc/status"
      # Negativ? Batterie lädt gerade, Positiv? Batterie entlädt
    - name: "EVCC Battery Power"
      unique_id: evcc_battery_Power
      state_topic: "evcc/site/batteryPower"
      unit_of_measurement: "W"
      availability_topic: "evcc/status"
      # Wallbox
    - name: "EVCC Loadpoint1 ChargePower"
      unique_id: evcc_loadpoint1_ChargePower
      state_topic: "evcc/loadpoints/1/chargePower"
      unit_of_measurement: "W"
      availability_topic: "evcc/status"
      # Kellerentfeuchter
    - name: "EVCC Loadpoint2 ChargePower"
      unique_id: evcc_loadpoint2_ChargePower
      state_topic: "evcc/loadpoints/2/chargePower"
      unit_of_measurement: "W"
      availability_topic: "evcc/status"
      # was kommt vom Dach v2?
    - name: "EVCC PV Power2"
      unique_id: evcc_pv_power2
      state_topic: "evcc/site/pvPower"
      #value_template: "{{ value | round(1) }}"
      unit_of_measurement: "W"
      availability_topic: "evcc/status"
      device_class: power

#
# for camera stuff to work
# see https://community.home-assistant.io/t/motioneye-integration/194350
#
stream:
# camera: !include cameras.yaml
#
#
#
input_boolean: !include input_booleans.yaml
binary_sensor: !include binary_sensors.yaml
rest_command: !include rest_commands.yaml
#
#
#
input_text:
  swalandline:
    initial: !secret swalandline
#
# https://www.home-assistant.io/integrations/google/
# deprecated with 2022.6
# google:
# client_id: !secret googleclientid
# client_secret: !secret googleclientsecret
#
# use https://community.home-assistant.io/t/how-to-keep-your-recorder-database-size-under-control/295795
#
recorder:
  db_url: !secret db_url
  purge_keep_days: 4
  exclude:
    entity_globs:
      - sensor.adguard*
      - sensor.watchman*
      - binary_sensor.*overheating
      - binary_sensor.*overpowering
      - device_tracker.*
      - sensor.iphone*
      - sensor.jphone*
      - sensor.stefans_ipad*
      - sensor.swaiphone*
      - sensor.thermostat_date*
      - sensor.fritz*
      - sensor.system*
      - switch.adguard*
      - sensor.smlpower_*
      - sensor.espresense_esppkidsgross*
      - binary_sensor.espresense_esppkidsgross*
    entities:
      #      - sensor.swaiphone_info
      #      - sensor.jphone_info
      #      - sensor.iphone_von_anna_info
      - sensor.smlreaderdeviceid
      - sensor.smlreadermanufacturer
      # must not exclude or energy dashboard does not work
      # - sensor.smlreadertotalenergyconsumption
      - sensor.smlreaderpower
      - sensor.roofac_wifi_signal
      - sensor.smlreaderpower
      - sensor.smlreadercounter
      - sensor.load_15m
      - sensor.load_1m
      - sensor.heating_differential
      - sensor.gas3_uptime
      - sensor.sleepac_uptime
      - sensor.roofac_uptime
      - sensor.boiler_total_heat_operating_time
      - sensor.roofac_wifi_signal
      - sensor.gas3_wifi_signal
      - sensor.smlpower_daily
      - sensor.smlpower_yearly
      - sensor.shelly25_og_schlafli_rssi
      - sensor.unavailable_entities
      - sensor.tesla_wall_connector_grid_frequency
      - sensor.tesla_wall_connector_grid_voltage
      - sensor.memory_use_percent
      - sensor.silvia_power_avg
      - sensor.shellys_silvia_power
      # - sensor.smlreadertotalenergyconsumption
      - sensor.espresense_esppkidsgross_espresense_esppkidsgross_free_mem
      - sensor.espresense_esppkidsgross_espresense_esppkidsgross_uptime
      - binary_sensor.espresense_esppkidsgross_espresense_esppkidsgross

  include:
    entities:
      - sensor.tesla_wall_connector_energy
      #      - camera.iphone6
      # - device_tracker.location_tracker
      - sensor.watermain_value
      - sensor.filtered_smlreadertotalenergyconsumption
#
#
#
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb
  max_retries: 3
  default_measurement: state
  include:
    entities:
      # - weather.home -> can be removed in influxdb
      #      - weather.openweathermap
      # - weather.accuweather
      #      - binary_sensor.heating_active
      #      - binary_sensor.warm_water_dhw_active
      - counter.kellerpumpe
      - counter.dew_index
      - climate.roofac
      #      - sensor.roofac_uptime
      #      - sensor.gas3_uptime
      - climate.sleepac
      #      - sensor.sleepac_uptime
      - sensor.hum_abs_basement
      #- sensor.smlreadertotalenergyconsumption -> remove me and switch to filtered
      - sensor.filtered_smlreadertotalenergyconsumption
      # floods the database as it comes in too often
      #      - sensor.smlreaderpower
      - sensor.influxdb_db_size
      - sensor.gasverbrauch
      - sensor.heidelberg_precipitation
      - sensor.tesla_last_charge_session
      - sensor.tesla_last_charging_session_kwh
      - sensor.tesla_wall_connector_state
      - sensor.tesla_wall_connector_energy
      - binary_sensor.tesla_wall_connector_contactor_closed
      - binary_sensor.tesla_wall_connector_vehicle_connected
      - sensor.heidelberg_temperature
      - sensor.swa_home_outdoor_temperature
    entity_globs:
      - sensor.shellys_keller*
      - sensor.boiler*
      - sensor.mixer*
      - sensor.thermostat*
      - sensor.solar*
      # - sensor.accuweather*
      # - sensor.openweathermap*
      - sensor.multi*
      - sensor.dew*
      - sensor.heating*
      - binary_sensor.boiler*
      - binary_sensor.mixer*
      - binary_sensor.solar*
      - number.boiler*
      - number.mixer*
      - number.thermostat*
      - number.solar*
      - select.boiler*
      - select.mixer*
      - select.thermostat*
      - select.solar*
#
#
counter:
  kellerpumpe:
    initial: 0
    step: 1
    icon: mdi:water-pump
#
# power and gas meters
#
utility_meter:
  gasverbrauch_hourly:
    source: sensor.gasverbrauch
    cycle: hourly
  gasverbrauch_daily:
    source: sensor.gasverbrauch
    cycle: daily
  gasverbrauch_weekly:
    source: sensor.gasverbrauch
    cycle: weekly
  gasverbrauch_monthly:
    source: sensor.gasverbrauch
    cycle: monthly
  gasverbrauch_yearly:
    source: sensor.gasverbrauch
    cycle: yearly
  #
  #
  smlpower_hourly:
    source: sensor.smlreadertotalenergyconsumption
    cycle: hourly
  smlpower_daily:
    source: sensor.smlreadertotalenergyconsumption
    cycle: daily
  smlpower_weekly:
    source: sensor.smlreadertotalenergyconsumption
    cycle: weekly
  smlpower_monthly:
    source: sensor.smlreadertotalenergyconsumption
    cycle: monthly
  smlpower_yearly:
    source: sensor.smlreadertotalenergyconsumption
    cycle: yearly
  #
  #
  # regen_daily:
  # source: sensor.regen_heute
  # cycle: daily

#
# for the spotify integration
# deprecated with 2022.6
# spotify:
# client_id: !secret spotify_clientid
# client_secret: !secret spotify_secret
#
# for spotcast (requirement of spotify-card)
#
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key
  country: DE #optional, added in 3.6.24
#
#
#
panel_custom:
  #  - name: Server Controls
  #    url_path: config/server_control # url_path needs to be unique for each panel_custom config
  #    sidebar_title: Server Controls
  #    sidebar_icon: mdi:server # https://materialdesignicons.com/
  #    module_url: /local/panel-redirect.js # 'local' is '/config/www/'
  - name: Logs
    url_path: config/logs
    sidebar_title: Logs
    sidebar_icon: mdi:math-log
    module_url: /local/panel-redirect.js
# - name: Basement
# url_path: lovelace/keller
# sidebar_title: -1
# sidebar_icon: mdi:home-floor-negative-1
# module_url: /local/panel-redirect.js
# - name: Ground Floor
# url_path: lovelace/eg
# sidebar_title: 0
# sidebar_icon: mdi:home-floor-0
# module_url: /local/panel-redirect.js
# - name: First Floor
# url_path: lovelace/og
# sidebar_title: 1
# sidebar_icon: mdi:home-floor-1
# module_url: /local/panel-redirect.js
# - name: Second Floor
# url_path: lovelace/dg
# sidebar_title: 2
# sidebar_icon: mdi:home-floor-2
# module_url: /local/panel-redirect.js
# - name: Einfahrt
# url_path: lovelace/outdoor
# sidebar_title: Einfahrt
# sidebar_icon: mdi:garage-variant
# module_url: /local/panel-redirect.js
#
#
#
shell_command:
  #  push_to_github: "/config/gitpush.sh > /dev/null 2>&1"
  push_to_github: "/config/gitpush.sh &> /dev/null"
  push_to_github2: /config/gitpush.sh
  push_to_github3: /bin/bash /config/gitpush.sh
#
# to show camera live feed on wall tablet: use browser_mod
# this section was version 1
#browser_mod:
#  prefix: "browser_"
#  devices:
#    4829eb14-9690bdf4:
#      name: Thinkpad
#    b174e12b-9abd3035:
#      name: Firetablet
#
#
#
rest:
  - authentication: basic
    username: ""
    password: ""
    scan_interval: 90
    resource: http://192.168.178.36/api/1/vitals
    sensor:
      - name: "Tesla last charge session"
        value_template: "{{ value_json.session_energy_wh }}"
        device_class: energy
        state_class: total_increasing
        unit_of_measurement: "Wh"
