# for us europeans
unit_of_measurement: km
time_format: 24
waze_region: EU
# log_level: debug+rawdata
devices:
  - device_name: swaiPhone
    name: Stefan
    picture: swa.jpg
  - device_name: jphone
    name: Julia
    picture: julia.jpg
  - device_name: iphone_von_anna
    name: Anna
    picture: anna.jpg
