
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml
  customize_glob:
    "binary_sensor.fenster*":
      device_class: window
#
# check out https://www.home-assistant.io/lovelace/dashboards-and-views/
#
# lovelace:
  # mode: yaml
  # resources:
    # - url: /local/lovelace-auto-entities/auto-entities.js
      # type: module
#
#
#
frontend:
  themes: !include_dir_merge_named themes

#
# uncomment to increase loglevel
#
# logger:
  # default: info
  # logs:
    # custom_components.icloud3.pyicloud_ic3: debug
    # custom_components.icloud3.device_tracker: debug

logger:
  default: warn
  logs:
    homeassistant.components.recorder: debug
# temporary solution as per https://github.com/emsesp/EMS-ESP/issues/756
    homeassistant.helpers.template: error

#
# to turn on my pc
#
wake_on_lan:
#
# Text to speech
#
tts:
  - platform: google_translate
    language: 'de'
    service_name: google_translate_say
    base_url: !secret base_url
#
#
#
zone: !include zones.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
notify: !include notifications.yaml
sensor: !include sensors.yaml
device_tracker: !include devicetrackers.yaml
#alert: !include alerts.yaml
http: !include http.yaml
cover: !include covers.yaml
volvooncall: !include volvo.yaml
switch: !include switches.yaml
homekit: !include homekit.yaml

#
# for camera stuff to work
# see https://community.home-assistant.io/t/motioneye-integration/194350
#
stream:
camera: !include cameras.yaml
#
#
#
input_boolean: !include input_booleans.yaml
binary_sensor: !include binary_sensors.yaml
rest_command: !include rest_commands.yaml
#
#
recorder:
  db_url: !secret db_url
  purge_keep_days: 7
  exclude:
    entity_globs:
      - sensor.adguard*
    entities:
      - sensor.icloud3_event_log
      - sensor.swaiphone_info
      - sensor.jphone_info
      - sensor.iphone_von_anna_info
#
#
#
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb
  max_retries: 3
  default_measurement: state
  include:
    entities:
      - weather.home
      - weather.openweathermap
      - weather.accuweather
      - binary_sensor.heating_active
      - binary_sensor.warm_water_dhw_active      
      - sensor.swaweathermetno
      - sensor.swaweathermetno_condition
      - sensor.swaweathermetno_templow
      - sensor.swaweathermetno_temphigh
      - counter.kellerpumpe
      - counter.dew_fans
      - climate.roofac
      - sensor.roofac_uptime
      - sensor.gas3_uptime
      - climate.sleepac
      - sensor.sleepac_uptime
      - sensor.regen_heute
      - sensor.rel_humidity
      - sensor.hum_abs_basement
    entity_globs:
      - sensor.boiler*
      - sensor.mixer*
      - sensor.thermostat*
      - sensor.solar*
      - sensor.accuweather*
      - sensor.multi*
      - sensor.dew*
      - sensor.heating*
      - sensor.gasverbrauch*
      - binary_sensor.boiler*
      - binary_sensor.mixer*
      - binary_sensor.solar*
#
#
counter:
    kellerpumpe:
      initial: 0
      step: 1
      icon: mdi:water-pump
    dew_fans:
      initial: 0
      step: 1
      icon: mdi:fan
#
#
utility_meter:
  gasverbrauch_hourly:
    source: sensor.gasverbrauch
    cycle: hourly
  gasverbrauch_daily:
    source: sensor.gasverbrauch
    cycle: daily
  gasverbrauch_weekly:  
    source: sensor.gasverbrauch
    cycle: weekly
  gasverbrauch_monthly:
    source: sensor.gasverbrauch
    cycle: monthly
  gasverbrauch_yearly:
    source: sensor.gasverbrauch
    cycle: yearly
#
#
  regen_daily:
    source: sensor.regen_heute
    cycle: daily