
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml
  customize_glob:
    "binary_sensor.fenster*":
      device_class: window
#
# check out https://www.home-assistant.io/lovelace/dashboards-and-views/
#
# lovelace:
  # mode: yaml
  # resources:
    # - url: /local/lovelace-auto-entities/auto-entities.js
      # type: module
#
# uncomment to increase loglevel
#
# logger:
  # default: info
  # logs:
    # custom_components.icloud3.pyicloud_ic3: debug
    # custom_components.icloud3.device_tracker: debug
#
# to turn on my pc
#
wake_on_lan:
#
# Text to speech
#
tts:
  - platform: google_translate
#
#
zone: !include zones.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
notify: !include notifications.yaml
sensor: !include sensors.yaml
device_tracker: !include devicetrackers.yaml
alert: !include alerts.yaml
http: !include http.yaml
cover: !include covers.yaml
volvooncall: !include volvo.yaml
switch: !include switches.yaml
#
# for camera stuff to work
# see https://community.home-assistant.io/t/motioneye-integration/194350
#
stream:
camera: !include cameras.yaml
input_boolean: !include input_booleans.yaml
binary_sensor: !include binary_sensors.yaml
rest_command: !include rest_commands.yaml
#
#
recorder:
  purge_keep_days: 3
  exclude:
    entities:
      - sensor.icloud3_event_log
