
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml
  customize_glob:
    "binary_sensor.fenster*":
      device_class: window
#
# check out https://www.home-assistant.io/lovelace/dashboards-and-views/
#
# lovelace:
  # mode: yaml
  # resources:
    # - url: /local/lovelace-auto-entities/auto-entities.js
      # type: module
#
#
#
# logger:
  # default: info
  # logs:
    # homeassistant.components.shelly: debug
    # aioshelly: debug 
#
# to turn on my pc
#
wake_on_lan:
#
# Text to speech
#
tts:
  - platform: google_translate
#
#
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
notify: !include notifications.yaml
sensor: !include sensors.yaml
device_tracker: !include devicetrackers.yaml
alert: !include alerts.yaml
http: !include http.yaml
cover: !include covers.yaml
volvooncall: !include volvo.yaml
switch: !include switches.yaml

