
#
# Alle Rolladen im Schlafzimmer
#
- platform: group
  name: Eltern-Schlafzimmer
  entities: 
   - cover.shelly25_rolladen_schlafzimmer_li
   - cover.shelly25_rolladen_elternbad

  # icon_template: >-
    # {% if state_attr('cover.eltern_schlafzimmer', 'current_position') | float > 0 %}
      # mdi:shutter-open
    # {% else %}
      # mdi:shutter
    # {% endif %}
#
# garage door
#
# there is only one button (!) so we only use turn_on
#
- platform: template
  covers:
    garage_door:
      device_class: garage
      friendly_name: "Garage Door"
      value_template: "{% if is_state('binary_sensor.shelly1_garage_input', 'on') %}closed{% else %}open{% endif %}"
      open_cover:
        service: switch.turn_on
        data:
          entity_id: switch.shelly1_garage
      close_cover:
        service: switch.turn_on
        data:
          entity_id: switch.shelly1_garage
      stop_cover:
        service: switch.turn_on
        data:
          entity_id: switch.shelly1_garage
      icon_template: >-
        {% if is_state('binary_sensor.shelly1_garage_input','off') %}
          mdi:garage-open
        {% else %}
          mdi:garage
        {% endif %}
