# ----------------------
# Reload Groups, Group Entities ...
# ----------------------

#
# omit the "notify." here
#
- platform: group
  name: all_ios_devices
  services:
  - service: mobile_app_jphone
  - service: mobile_app_iphonebwi
  - service: mobile_app_stefans_ipad
  - service: mobile_app_swaiphone
  - service: mobile_app_iphone_von_anna
#
# omit the "notify." here
#
- platform: group
  name: all_ios_parent_phones
  services:
  - service: mobile_app_swaiphone
#  - service: mobile_app_jphone
#
# dont use message here, will be configured in alert itself
#
- platform: group
  name: urgent_notification
  services:
    - service: all_ios_parent_phones
      data:
        title: 'Hinweis'
        data:
          push:
            sound: 
              name: default
              critical: 1
              volume: 0.3
