# ----------------------
# Reload Groups, Group Entities ...
# ----------------------

#
# persistent notifications -> update badge count
#
- platform: group
  name: all_notify
  services:
    - service: mobile_app_ipadbwipro11
    - service: mobile_app_iphone15b

# Example configuration.yaml entry from https://www.home-assistant.io/integrations/smtp/
# create an app password, see https://support.google.com/mail/answer/185833
# used in tesla notification
- platform: smtp
  name: email_notification
  server: "smtp.gmail.com"
  port: 587
  timeout: 15
  sender: !secret my_email
  encryption: starttls
  username: !secret my_email
  password: !secret my_email_app_password
  recipient: !secret my_email
  sender_name: "HA" #optional
  debug: true
