#
# Configuration | YAML configuration reloading | Reload Template Entities
#

- platform: uptime
#
#
#
- platform: fritzbox_callmonitor
  name: FritzPhone
  host: 192.168.178.1
  username: hacallmon
  password: !secret hacallmon_password
  phonebook: 0
  prefixes:
    - '+49'
    - '+496221'
    - '06221'
#
#
#
- platform: systemmonitor
  resources:
    - type: memory_use_percent
    - type: processor_temperature
    - type: last_boot
    - type: load_1m
    - type: load_5m
    - type: load_15m
#
# gives a new entity after restart
#
- platform: template
  sensors:
#
#
#
    solar_angle:
      friendly_name: "Sun angle"
      unit_of_measurement: 'degrees'
      value_template: "{{ state_attr('sun.sun', 'elevation') }}"
#
# fake sensor
#
    swa_fake:
      friendly_name: Fake sensor
      value_template: "off"
#
#
#
    regen_heute:
      friendly_name: met.no Precipitation
      value_template: "{{ state_attr('weather.homeassistant', 'forecast')[0].precipitation }}"
