#
# Configuration | YAML configuration reloading | Reload Template Entities
#

- platform: uptime
#
#
#
- platform: fritzbox_callmonitor
  name: FritzPhone
  host: 192.168.178.1
  username: hacallmon
  password: !secret hacallmon_password
  phonebook: 0
  prefixes:
    - '+49'
    - '+496221'
    - '06221'
#
#
#
- platform: systemmonitor
  resources:
    - type: memory_use_percent
    - type: processor_temperature
    - type: last_boot
    - type: load_1m
    - type: load_5m
    - type: load_15m
#
# gives a new entity after restart
#
- platform: template
  sensors:
#
#
#
    solar_angle:
      friendly_name: "Sun angle"
      unit_of_measurement: 'degrees'
      value_template: "{{ state_attr('sun.sun', 'elevation') }}"
#
# fake sensor
#
    swa_fake:
      friendly_name: Fake sensor
      value_template: "off"
#
#
#
    regen_heute:
      friendly_name: met.no Precipitation
      value_template: "{{ state_attr('weather.homeassistant', 'forecast')[0].precipitation }}"
#
#
#
- platform: sql
  db_url: !secret db_url
  queries:
    - name: DB size
      query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1024, 1) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
      column: "value"
      unit_of_measurement: kB
#
#
#
- platform: template
  sensors:
    heating_differential:
      friendly_name: "Flow-Ret diff"
      unit_of_measurement: '°C'
      icon_template: 'mdi:format-align-middle'
      value_template: "{{ (states('sensor.boiler_current_flow_temperature') | float - states('sensor.boiler_return_temperature') | float) | round(1) }}"
