esphome:
  name: foo
  platform: ESP32
  board: esp-wrover-kit

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "f2dca62e8f3a14f06b223c7e2f627e90"

wifi:
  use_address: 192.168.178.93
  ssid: !secret wlan_name
  password: !secret wlan_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Foo Fallback Hotspot"
    password: "yeQ5lkOxXgXG"

captive_portal:
