###################################################################################################
## PACKAGE: Unavailable Entities Sensor v2.4
## DESCRIPTION: Count and list entities with a state of unknown or unavailable
## REQUIREMENTS: Home Assistant v2024.8
## USAGE: https://github.com/jazzyisj/unavailable-entities-sensor/blob/main/README.md
###################################################################################################

#REQUIRED - List of disabled device entities
command_line:
  sensor:
      name: Disabled Device Entities
      unique_id: disabled_device_entities
      json_attributes:
        - entities
      value_template: "{{ value_json.entities | length }}"
      command: 'jq ''.data.entities |= map(select(.disabled_by? != null) | {entity_id: .entity_id}) | del(.data.deleted_entities) | flatten | .[3]'' < .storage/core.entity_registry'

#REQUIRED - Count of unavailable entities
template:
  - sensor:
      - name: "Unavailable Entities"
        unique_id: unavailable_entities
        icon: "{{ iif(states(this.entity_id)|int(-1) > 0, 'mdi:alert-circle', 'mdi:check-circle') }}"
        state_class: measurement
        state: >
          {% set entities = state_attr('group.unavailable_entities', 'entity_id') %}
          {{ entities | count if entities != none else -1 }}

#REQUIRED - Group of individually ignored entities
group:
  ignored_entities:
    entities:
      - sensor.evcc_garage_charge_remaining_duration
      - sensor.evcc_garage_charge_remaining_energy
      - sensor.evcc_garage_charge_total_import
      - sensor.evcc_garage_effective_plan_time
      - sensor.evcc_garage_phases_enabled
      - sensor.evcc_garage_plan_projected_end
      - sensor.evcc_garage_plan_projected_start
      - sensor.evcc_garage_pv_remaining
      - sensor.evcc_garage_session_co2_per_kwh
      - sensor.evcc_garage_vehicle_plans_soc
      - sensor.evcc_garage_vehicle_plans_time
      - sensor.evcc_haus_charge_remaining_duration
      - sensor.evcc_haus_charge_remaining_energy
      - sensor.evcc_haus_effective_plan_time
      - sensor.evcc_haus_phases_enabled
      - sensor.evcc_haus_plan_projected_end
      - sensor.evcc_haus_plan_projected_start
      - sensor.evcc_haus_pv_remaining
      - sensor.evcc_haus_session_co2_per_kwh
      - sensor.evcc_tariff_co2
      - sensor.evcc_tariff_co2_home
      - sensor.evcc_tariff_co2_loadpoints
      - sensor.evcc_tariff_feed_in
      - binary_sensor.boiler_dhw_active
      - binary_sensor.boiler_dhw_charging
      - binary_sensor.boiler_dhw_recharging
      - binary_sensor.boiler_dhw_temperature_ok
      - binary_sensor.doors
      - binary_sensor.fenster_anna
      - binary_sensor.fenster_sw
      - binary_sensor.shelly25_og_clara_overheating
      - binary_sensor.swaphone16_focus
      - binary_sensor.system_ntp_status
      - binary_sensor.t1_windows
      - binary_sensor.wintergarten_button_lock_on_device
      - binary_sensor.wintergarten_button_lock_via_ui
      - cover.shelly25_og_clara
      - lock.doors
      - notify.tibber
      - number.boiler_time_to_next_maintenance
      - number.charge_limit
      - number.charging_amps
      - number.evcc_battery_grid_charge_limit
      - number.evcc_garage_smart_cost_limit
      - number.evcc_haus_smart_cost_limit
      - number.thermostat_dhw2_charge_duration
      - number.thermostat_dhw2_daily_heating_time
      - number.thermostat_dhw2_disinfection_time
      - number.thermostat_dhw2_set_low_temperature
      - number.thermostat_dhw2_set_temperature
      - number.thermostat_hc1_room_humidity_from_remote
      - number.thermostat_hc1_room_temperature_from_remote
      - number.thermostat_hc2_room_humidity_from_remote
      - number.thermostat_hc2_room_temperature_from_remote
      - number.thermostat_hc3_room_humidity_from_remote
      - number.thermostat_hc3_room_temperature_from_remote
      - person.mieter2
      - person.tablet
      - select.boiler_maintenance_scheduled
      - select.boiler_reset
      - select.cabin_overheat_protection
      - select.t1_heated_seat_rear_center
      - select.t1_heated_seat_rear_left
      - select.t1_heated_seat_rear_right
      - select.thermostat_dhw2_circulation_pump_mode
      - select.thermostat_dhw2_disinfection_day
      - select.thermostat_dhw2_mode
      - sensor.anna_bad_battery_level
      - sensor.anna_battery_level
      - sensor.annas_ipad_battery
      - sensor.apple_watch_von_julia_battery
      - sensor.arrival_time
      - sensor.boiler_dhw_active_time
      - sensor.boiler_dhw_current_tap_water_flow
      - sensor.boiler_dhw_set_temperature
      - sensor.boiler_dhw_starts
      - sensor.boiler_dhw_type
      - sensor.boiler_last_error_code
      - sensor.charger_power
      - sensor.charging_rate
      - sensor.dew_difference
      - sensor.dewpoint_basement
      - sensor.distance_to_arrival
      - sensor.energy_added
      - sensor.ipadbwipro11_battery
      - sensor.iphone_von_anna_2_battery
      - sensor.iphone_von_konstantin_battery_2
      - sensor.jphone16_battery_2
      - sensor.multi_og_aussen_humidity
      - sensor.multi_og_aussen_pressure
      - sensor.multi_og_aussen_temperature
      - sensor.odometer
      - sensor.og_aussen_battery_level
      - sensor.pool_bssid
      - sensor.pool_esphome_version
      - sensor.pool_ip
      - sensor.pool_orp
      - sensor.pool_ph
      - sensor.pool_ssid
      - sensor.pool_temp
      - sensor.pool_uptime
      - sensor.pool_wifi_signal
      - sensor.range
      - sensor.shelly25_og_clara_energy
      - sensor.shelly25_og_clara_power
      - sensor.spotify_swa72_song_tempo
      - sensor.stefan_s_2nd_fire_next_alarm_2
      - sensor.stefan_s_2nd_fire_next_reminder_2
      - sensor.stefan_s_2nd_fire_next_timer_2
      - sensor.stefan_west_battery_level
      - sensor.stefan_west_temperature
      - sensor.swaphone16_activity
      - sensor.swaphone16_audio_output
      - sensor.swaphone16_battery
      - sensor.swaphone16_bssid
      - sensor.swaphone16_connection_type
      - sensor.swaphone16_distance
      - sensor.swaphone16_floors_ascended
      - sensor.swaphone16_floors_descended
      - sensor.swaphone16_geocoded_location
      - sensor.swaphone16_last_update_trigger
      - sensor.swaphone16_sim_1
      - sensor.swaphone16_sim_2
      - sensor.swaphone16_ssid
      - sensor.swaphone16_steps
      - sensor.swaphone16_storage
      - sensor.temperature_inside
      - sensor.temperature_outside
      - sensor.thermostat_dhw2_extra
      - sensor.thermostat_error_code
      - sensor.time_charge_complete
      - sensor.tpms_front_left
      - sensor.tpms_front_right
      - sensor.tpms_rear_left
      - sensor.tpms_rear_right
      - sensor.watermain_fwversion
      - sensor.watermain_hostname
      - sensor.watermain_interval
      - sensor.watermain_ip
      - sensor.watermain_mac
      - sensor.wintergarten_electric_current
      - sensor.wintergarten_power_consumption
      - sensor.wintergarten_temperature
      - sensor.wintergarten_total_energy
      - sensor.wintergarten_voltage
      - siren.garagecam_siren
      - switch.boiler_dhw_disinfecting
      - switch.boiler_dhw_one_time_charging
      - switch.garage_inside_onvif_autofocus
      - switch.garage_inside_onvif_ir_lamp
      - switch.garage_inside_onvif_wiper
      - switch.heated_steering
      - switch.livingroom_autofocus
      - switch.livingroom_ir_lamp
      - switch.livingroom_wiper
      - switch.sentry_mode
      - switch.thermostat_dhw2_charge
      - switch.thermostat_dhw2_daily_heating
      - switch.thermostat_dhw2_disinfecting
      - switch.valet_mode
      - switch.wintergarten
      - text.boiler_next_maintenance_date
      - binary_sensor.eg_freezer
      - select.evcc_garage_limit_soc
      - select.evcc_garage_min_soc
      - sensor.echo_clara_volume
      - sensor.eg_freezer_battery_level
      - sensor.heating_room_2anna

#REQUIRED - Create and update the monitored entities group. Updates once per minute.
automation:
  - id: update_unavailable_entities_group
    alias: "Update Unavailable Entities Group"
    description: "Update unavailable entities group."
    mode: single
    max_exceeded: silent
    triggers:
      - trigger: event
        event_type: call_service
        event_data:
          domain: group
          service: reload

      - trigger: time_pattern
        minutes: "/1"
    actions:
      - action: group.set
        data:
          object_id: unavailable_entities
          entities: >
            {% set ignore_seconds = 60 %}
            {% set ignore_label = 'ignored' %}
            {% set ignored_domains = ['button', 'conversation', 'event', 'group', 'image',
                'input_button', 'input_text', 'remote', 'tts', 'scene', 'stt', 'update'] %}
            {% set ignore_ts = (now().timestamp() - ignore_seconds)|as_datetime %}
            {% set disabled_device_entities = state_attr('sensor.disabled_device_entities', 'entities')
                | regex_replace(find='\[|\]|\{|\}|\'entity_id\':', replace='') %}
            {% set ignored_devices = label_devices(ignore_label | lower) %}
            {% set ignored_device_entities = namespace(value=[]) %}
            {% for device in ignored_devices %}
              {% set ignored_device_entities.value = ignored_device_entities.value + device_entities(device) %}
            {% endfor %}
            {{ states
                | rejectattr('domain', 'in', ignored_domains)
                | rejectattr('entity_id', 'in', disabled_device_entities)
                | rejectattr('entity_id', 'in', state_attr('group.ignored_entities', 'entity_id'))
                | rejectattr('entity_id', 'in', ['group.unavailable_entities', 'group.ignored_entities'])
                | rejectattr('entity_id', 'in', ignored_device_entities.value)
                | rejectattr('entity_id', 'in', label_entities(ignore_label | lower))
                | rejectattr('last_changed', 'ge', ignore_ts)
                | rejectattr('entity_id', 'contains', 'disk_elitedesk')
                | rejectattr('entity_id', 'contains', 'fritz_box_7490')
                | rejectattr('entity_id', 'contains', 'echo_dot')     
                | rejectattr('entity_id','search','.r1_')
                | rejectattr('entity_id','search','.iphoneclara11')
                | rejectattr('entity_id','search','.riphone')
                | rejectattr('entity_id','search','.this_device')
                | rejectattr('entity_id','search','_internet_access')
                | rejectattr('entity_id','search','device_tracker')
                | rejectattr('entity_id','search','battery_state')
                | rejectattr('entity_id','search','battery_last_replaced')
                | selectattr('state', 'in', ['unknown', 'unavailable'])
                | map(attribute='entity_id') | list | sort }}

  #OPTIONAL - Example notfication automation to demonstrate how you can utilize this sensor. (See example folder for more.)
  - id: unavailable_entities_notification
    alias: "Unavailable Entities Notification"
    description: "Create persistent notification if unavailable entities, dismiss if none."
    mode: restart
    triggers:
      - trigger: state
        entity_id: group.unavailable_entities
        attribute: entity_id
        to: ~
        for: 5 # throttle triggers and prevent blank notifications
    conditions:
      - condition: template
        alias: "Sensor state is a valid numerical value"
        value_template: "{{ is_number(states('sensor.unavailable_entities')) }}"
    actions:
      - if:
          - condition: numeric_state
            entity_id: sensor.unavailable_entities
            below: 1
        then:
          - action: persistent_notification.dismiss
            data:
              notification_id: unavailable_entities
        else:
          - action: persistent_notification.create
            data:
              notification_id: unavailable_entities
              title: "Unavailable Entities"
              message: "{{ state_attr('group.unavailable_entities', 'entity_id') | join('\n') }}"
