###################################################################################################
## Package - Unavailable Entities Sensor
## Count and list entities with a state of unavailable, unknown, or none (null)
## See README for customization options.
## https://github.com/jazzyisj/unavailable-entities-sensor/blob/main/README.md
###################################################################################################

# NOTE: Home Assistant v2021.12 required.  For older versions please see README
# REQUIRED - This is the template sensor
template:
  - sensor:
      - name: "Unavailable Entities"
        unique_id: unavailable_entities
        icon: "{{ 'mdi:alert-circle' if states('sensor.unavailable_entities')|int(0) > 0 else 'mdi:check-circle' }}"
        unit_of_measurement: entities
        state: >
          {% if state_attr('sensor.unavailable_entities','entity_id') != none %}
            {{ state_attr('sensor.unavailable_entities','entity_id')|count }}
          {% endif %}
        attributes:
          entity_id: >
            {% if state_attr('group.ignored_unavailable_entities','entity_id') != none %}
              {% set ignore_seconds = 60 %}
              {% set ignore_ts = (now().timestamp() - ignore_seconds)|as_datetime %}
              {% set entities = states|rejectattr('domain','in',['group','button'])|selectattr('state','in',['unavailable','unknown','none'])|list %}
              {% set buttons = states.button|selectattr('state','eq','unavailable')|list %}
              {{ (entities + buttons)
                |rejectattr('entity_id','in',state_attr('group.ignored_unavailable_entities','entity_id'))
                |rejectattr('entity_id', 'search', '(sensor.browser_|media_player.browser_|light.browser_|iphone6|hp_laserjet_200|binary_sensor.boiler_ww_|sensor.stefan_s_2nd_fire_next|sensor.stefans_echo_dot_next)')
                |rejectattr('last_changed','ge',ignore_ts)
                |map(attribute='entity_id')|list }}
            {% endif %}

# REQUIRED - Add any entities you do not wish to monitor in this group.
# IMPORTANT - This group MUST exist even if empty for sensor template to render.
group:
  ignored_unavailable_entities:
    entities:
      - sensor.unavailable_entities # prevent template loop warnings?
      - binary_sensor.updater # always unknown after restart
# swa custom stuff
      - binary_sensor.731a166f_25d1d5bb
      - binary_sensor.731a166f_25d1d5bb_browser_charging
      - binary_sensor.731a166f_25d1d5bb_browser_dark_mode
      - binary_sensor.731a166f_25d1d5bb_browser_fullykiosk
      - binary_sensor.9456b1a3_208a3c42
      - binary_sensor.9456b1a3_208a3c42_browser_dark_mode
      - binary_sensor.9456b1a3_208a3c42_browser_fullykiosk
      - binary_sensor.boiler_charging_type
      - binary_sensor.boiler_dhw_active
      - binary_sensor.boiler_dhw_charging
      - binary_sensor.boiler_dhw_recharging
      - binary_sensor.boiler_dhw_temperature_ok
      - binary_sensor.boiler_disinfecting
      - binary_sensor.fritz_box_7490_connectivity
      - binary_sensor.livingroom_file_stored
      - binary_sensor.livingroom_motion
      - binary_sensor.shellys_keller_entfeuchter_firmware_update
      - climate.dg_stefan
      - device_tracker.android_2
      - device_tracker.anna_t430
      - device_tracker.apple_watch_von_julia
      - device_tracker.apple_watch_von_julia_2
      - device_tracker.apple_watch_von_julia_4
      - device_tracker.galaxy_a53_5g
      - device_tracker.galaxy_tab_s6_lite
      - device_tracker.honor_7x_715d683076b6dc72
      - device_tracker.ipad_von_clausw
      - device_tracker.ipadbwipro11_2
      - device_tracker.iphone
      - device_tracker.iphone_2
      - device_tracker.iphone_2_2
      - device_tracker.iphone_5
      - device_tracker.iphone_von_anna
      - device_tracker.iphone_von_anna_2
      - device_tracker.iphone_von_anna_2_2
      - device_tracker.iphone_von_anna_2_3
      - device_tracker.iphone_von_anna_2_4
      - device_tracker.iphone_von_anna_2_5
      - device_tracker.iphone_von_anna_6
      - device_tracker.iphonebwi
      - device_tracker.iphonebwi12_3
      - device_tracker.iphoneclarase2020
      - device_tracker.iphoneclarase2020_2
      - device_tracker.jpad_air_2_2
      - device_tracker.jpad_air_2_3
      - device_tracker.jpad_air_2_5
      - device_tracker.jphone_3
      - device_tracker.jphone_4
      - device_tracker.jphone_6
      - device_tracker.laptop_1qnmles6
      - device_tracker.pc_192_168_178_38
      - device_tracker.pc_192_168_178_41
      - device_tracker.pc_192_168_178_46_2
      - device_tracker.pc_192_168_178_57
      - device_tracker.pc_192_168_178_58
      - device_tracker.pc_192_168_178_60
      - device_tracker.pc_192_168_178_62
      - device_tracker.pc_192_168_178_77
      - device_tracker.pc_192_168_178_79
      - device_tracker.peters_iphone
      - device_tracker.pool
      - device_tracker.s20_von_gerd
      - device_tracker.samsung_galaxy_s7
      - device_tracker.shellys_poolpump
      - device_tracker.stefans_ipad_3
      - device_tracker.t430_lan
      - device_tracker.t430_vm_wiso
      - light.731a166f_25d1d5bb_screen
      - light.9456b1a3_208a3c42_screen
      - light.dimmable_light_3
      - light.ikea_repeater_1
      - light.ikea_repeater_2
      - media_player.731a166f_25d1d5bb
      - media_player.9456b1a3_208a3c42
      - media_player.fire_tablet_media_player
      - media_player.stefans_2_echo_dot
      - person.tablet
      - sensor.731a166f_25d1d5bb_browser_battery
      - sensor.731a166f_25d1d5bb_browser_height
      - sensor.731a166f_25d1d5bb_browser_path
      - sensor.731a166f_25d1d5bb_browser_user
      - sensor.731a166f_25d1d5bb_browser_useragent
      - sensor.731a166f_25d1d5bb_browser_visibility
      - sensor.731a166f_25d1d5bb_browser_width
      - sensor.9456b1a3_208a3c42_browser_height
      - sensor.9456b1a3_208a3c42_browser_path
      - sensor.9456b1a3_208a3c42_browser_user
      - sensor.9456b1a3_208a3c42_browser_useragent
      - sensor.9456b1a3_208a3c42_browser_visibility
      - sensor.9456b1a3_208a3c42_browser_width
      - sensor.apple_watch_von_julia_battery_state
      - sensor.apple_watch_von_julia_battery_state_2
      - sensor.apple_watch_von_julia_battery_state_4
      - sensor.boiler_dhw_active_time
      - sensor.boiler_dhw_current_tap_water_flow
      - sensor.boiler_dhw_set_temperature
      - sensor.boiler_dhw_starts
      - sensor.boiler_dhw_type
      - sensor.hacs
      - sensor.ipadbwipro11_battery_state_2
      - sensor.iphone_battery_state
      - sensor.iphone_von_anna_2_battery_state
      - sensor.iphone_von_anna_2_battery_state_3
      - sensor.iphone_von_anna_2_battery_state_4
      - sensor.iphone_von_anna_2_battery_state_5
      - sensor.iphone_von_anna_battery_state_2
      - sensor.iphone_von_konstantin_battery_state
      - sensor.iphone_von_konstantin_battery_state_2
      - sensor.iphonebwi12_battery_state_2
      - sensor.iphoneclarase2020_battery_state
      - sensor.iphoneclarase2020_battery_state_2
      - sensor.jpad_air_2_battery_state
      - sensor.jpad_air_2_battery_state_2
      - sensor.jpad_air_2_battery_state_4
      - sensor.jphone_battery_state_2
      - sensor.jphone_battery_state_3
      - sensor.jphone_battery_state_5
      - sensor.solcast_api_remaining
      - sensor.stefans_ipad_battery_state_2
      - sensor.stefans_ipad_geocoded_location
      - switch.android_2_internet_access
      - switch.anna_t430_internet_access
      - switch.boiler_dhw_disinfecting
      - switch.boiler_dhw_one_time_charging
      - switch.fritz_box_7490_port_forward_home_assistant
      - switch.fritz_box_7490_wi_fi_hades
      - switch.galaxy_a53_5g_internet_access
      - switch.galaxy_tab_s6_lite_internet_access
      - switch.honor_7x_715d683076b6dc72_internet_access
      - switch.ipad_von_clausw_internet_access
      - switch.iphone_internet_access
      - switch.iphone_internet_access_2
      - switch.iphone_von_anna_internet_access
      - switch.laptop_1qnmles6_internet_access
      - switch.pc_192_168_178_38_internet_access
      - switch.pc_192_168_178_41_internet_access
      - switch.pc_192_168_178_46_internet_access_2
      - switch.pc_192_168_178_57_internet_access
      - switch.pc_192_168_178_58_internet_access
      - switch.pc_192_168_178_60_internet_access
      - switch.pc_192_168_178_62_internet_access
      - switch.pc_192_168_178_77_internet_access
      - switch.pc_192_168_178_79_internet_access
      - switch.peters_iphone_internet_access
      - switch.s20_von_gerd_internet_access
      - switch.samsung_galaxy_s7_internet_access
      - switch.stefans_echo_dot_repeat_switch
      - switch.stefans_echo_dot_shuffle_switch
      - switch.swajpad_internet_access
      - switch.t430_lan_internet_access
      - switch.t430_vm_wiso_internet_access
# pool stuff 
      - switch.shellys_poolpump_internet_access
      - switch.pool_internet_access
      - sensor.temp
      - binary_sensor.shellys_poolpump_overheating
      - binary_sensor.shellys_poolpump_overpowering
      - button.shellys_poolpump_ota_update
      - button.shellys_poolpump_reboot
      - sensor.pool_bssid
      - sensor.pool_esphome_version
      - sensor.pool_ip
      - sensor.pool_orp
      - sensor.pool_ph
      - sensor.pool_ssid
      - sensor.pool_temp
      - sensor.pool_uptime
      - sensor.pool_wifi_signal
      - sensor.shellys_poolpump_energy
      - sensor.shellys_poolpump_power
      - sensor.ph
      - switch.shellys_poolpump
# alexa stuff
      - sensor.this_device_next_alarm
      - sensor.this_device_next_reminder
      - sensor.this_device_next_timer
# indoor cam
      - binary_sensor.livingroom_cell_motion_detection
# tesla integration
      - sensor.arrival_time
      - sensor.distance_to_arrival
      - sensor.time_charge_complete
      - device_tracker.destination_location_tracker
# aussen temp
      - sensor.multi_og_aussen_humidity
      - sensor.multi_og_aussen_pressure
      - sensor.multi_og_aussen_temperature
      - sensor.og_aussen_battery_level
# Misc
      - sensor.system_tx_reads
      - sensor.system_tx_writes
      - switch.livingroom_autofocus
      - switch.livingroom_ir_lamp
      - switch.livingroom_wiper
      - update.gas3_firmware
      - update.roofac_firmware
      - update.sleepac_firmware
      - sensor.solar_cylinder_pump_modulation_ps5
      - sensor.solar_maximum_tank_temperature
      - sensor.solar_pump_modulation_ps1
      - sensor.solar_pump_working_time
      - sensor.solar_tank_bottom_temperature_ts2
# 

# OPTIONAL - filter template loop warnings from the Home Assistant log.
logger:
  filters:
    homeassistant.components.template.template_entity:
      - "Template loop detected while processing event"

# OPTIONAL Example automation to demonstrate how you can utilize this sensor
automation:
  - id: unavailable_entities_notification
    alias: "Unavailable Entities Notification"
    description: "Create persistent notification if there are unavailable entities, dismiss if none."
    mode: restart
    trigger:
      - platform: state
        entity_id: sensor.unavailable_entities
        to: ~
    condition:
      - condition: template
        value_template: >
          {{ is_number(trigger.from_state.state)
              and is_number(trigger.to_state.state) }}
    action:
      - choose:
          conditions:
            - condition: numeric_state
              entity_id: sensor.unavailable_entities
              below: 1
          sequence:
            - service: persistent_notification.dismiss
              data:
                notification_id: unavailable_entities
        default:
          - service: persistent_notification.create
            data:
              title: "Unavailable Entities"
              message: >
                - {{ expand(state_attr('sensor.unavailable_entities','entity_id'))
                      |map(attribute='entity_id')|join('\n- ') }}
              notification_id: unavailable_entities
